# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - refs/heads/feature
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/feature
jobs:
- job: terraform-build
  displayName: terraform-build
  timeoutInMinutes: 10
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: true
      OverWrite: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: tf-webapp'
    inputs:
      PathtoPublish: artifacts
      ArtifactName: tf-webapp
...
